### ISSUE TITLE
Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...

### ISSUE THREAD

**Issue by jascodin** [zademeadowshk/NEW-2025-Solana-Raydium-Sniper-Trading-Bot#20]
Having this issue Server responded with 429 Too Many Requests.  Retrying after 2000ms delay...

It still buys and sells correctly, but keeps giving me this error endlessly

**Comment by zademeadowshk** [comment]
that's an issue people are facing using quicknode rpc nodes, try using helius, it's better

**Comment by jascodin** [comment]
already on helius

**Comment by zademeadowshk** [comment]
> something to do with your env file then, you're making the bot perform way too many action within milliseconds
> 

correct, 
if the bot is working for y'all consider giving it a star guys!

**Comment by zademeadowshk** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
