### ISSUE TITLE
Error confirming buy tx

### ISSUE THREAD

**Issue by pede** [zademeadowshk/NEW-2025-Solana-Raydium-Sniper-Trading-Bot#27]
I get this error on every bot buy, what could be wrong?

```
[11:55:15.032] DEBUG:
    InstructionError: [
      3,
      {
        "Custom": 40
      }
    ]
[11:55:15.032] INFO: Error confirming buy tx
```

**Comment by zademeadowshk** [comment]
this happens when your set amount per trade is let's say 1 wsol and you wallet has less than 1 wsol...
so it cant buy the token

**Comment by zademeadowshk** [comment]
New Updates:
Fastest Solana Mainnet API Integrated
Advanced Rug Check with Top % Holders & Potential Fake Volume Bundler Detector
Auto Snipe Ongoing Hype Launches
Slippage %

Remove The Previous Versions Completely & Install The New Zip File, & Run The Bot ❤️
