### ISSUE TITLE
RPC Endpoint is not set

### ISSUE THREAD

**Issue by FeroAbi** [zademeadowshk/NEW-2025-Solana-Raydium-Sniper-Trading-Bot#33]
Hey 

I always get the same issue. I tried with helius and quick node and copying the addresses into to env document. I always get ERROR: RPC_ENDPOINT is not set. What am I doing wrong?

**Comment by zademeadowshk** [comment]
make sure the env file is .env
the extension shud be .env
share a picture of what your bot folder looks like

**Comment by FeroAbi** [comment]
it won't let me name the file .env
<img width="228" alt="Bildschirmfoto 2024-12-19 um 18 49 17" src="https://github.com/user-attachments/assets/e858c76e-6ab9-4b39-b098-daf632f3d6db" />

**Comment by FeroAbi** [comment]
worked. Now I get some other issues:

(node:7907) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by zademeadowshk** [comment]
correct if you're profiting using the bot, please consider giving us a star ⭐

**Comment by FeroAbi** [comment]
yeah I started it and all my sol got stolen. Thanks for that
